# Generated by Django 6.0.6 on 2026-07-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Customer', 'Customer')], max_length=100, null=True),
        ),
    ]
